# Generated by Django 5.0.3 on 2024-03-28 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quickstart", "0002_alter_caregiver_consent_alter_caregivertype_consent"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("consent_title", models.CharField(max_length=256)),
                ("consent_url", models.CharField(max_length=256)),
            ],
        ),
        migrations.RenameField(
            model_name="consent",
            old_name="permission_to_communicate",
            new_name="permission_to_email",
        ),
        migrations.RemoveField(
            model_name="caregiver",
            name="relationship_to_client",
        ),
        migrations.RemoveField(
            model_name="caregivertype",
            name="relationship_to_client",
        ),
        migrations.AddField(
            model_name="consent",
            name="permission_to_text",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="consent",
            name="contact_me",
            field=models.CharField(max_length=55),
        ),
    ]
