# Generated by Django 5.0.3 on 2024-03-29 01:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quickstart", "0004_caregivertype_relationship_to_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="caregiver",
            name="relationship_to_client",
            field=models.CharField(default="name of relationship", max_length=155),
            preserve_default=False,
        ),
    ]
