# Generated by Django 5.0.3 on 2024-04-02 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quickstart", "0005_caregiver_relationship_to_client"),
    ]

    operations = [
        migrations.CreateModel(
            name="SignedConsent",
            fields=[
                (
                    "consent_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="quickstart.consent",
                    ),
                ),
                ("image_base64", models.CharField(max_length=4096)),
            ],
            bases=("quickstart.consent",),
        ),
    ]
