# Generated by Django 5.0.3 on 2024-04-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quickstart", "0006_signedconsent"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoredConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=256)),
                ("name_on_health_card", models.CharField(max_length=256)),
                ("pdf_url", models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name="signedconsent",
            name="image_base64",
            field=models.CharField(max_length=8192),
        ),
    ]
