# Generated by Django 5.0.3 on 2024-04-02 18:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quickstart", "0007_storedconsent_alter_signedconsent_image_base64"),
    ]

    operations = [
        migrations.RenameField(
            model_name="storedconsent",
            old_name="name_on_health_card",
            new_name="health_card_number",
        ),
    ]
